name: Update Formulas
on:
  schedule:
    # https://crontab.guru
    # * is a special character in YAML, so this string needs to be quoted
    - cron: '0 8 * * *'
jobs:
  formulas:
    name: Formulas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Formulas
        uses: ./.github/actions/update-formulas
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: Milad Irannejad
          git_user_email: moorara@users.noreply.github.com
          git_user_signing_key: ${{ secrets.GPG_PRIVATE_KEY }}
